import Footer from "@/components/base/footer/footer";
import Header from "@/components/base/header/header";
import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import styles from "./layout.module.css";

const pretendard = localFont({
	src: "../assets/fonts/PretendardVariable.woff2",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko">
			<body className={pretendard.className}>
				<div className={styles.container}>
					<Header />
					<main className={styles.main}>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
